version: '3.8'
services:
  app:
    build: app
    ports:
      - "8080:8080"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/base?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://172.25.33.133:3307/base?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: $4ppUs3rmysql#
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-mysql-network

  mysql:
    image: mysql:8.0.24
    environment:
      MYSQL_ROOT_PASSWORD: Mavg300579*
      MYSQL_DATABASE: base
      MYSQL_USER: appuser
      MYSQL_PASSWORD: $4ppUs3rmysql#
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spring-mysql-network
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       timeout: 20s
       retries: 10

networks:
  spring-mysql-network:
    driver: bridge

volumes:
  db_data: