const localeText1 = {
    noRowsLabel: 'No hay filas',
    noResultsOverlayLabel: 'No se encontraron resultados.',
    errorOverlayDefaultLabel: 'Ha ocurrido un error.',
    toolbarDensity: 'Densidad',
    toolbarDensityLabel: 'Densidad',
    toolbarDensityCompact: 'Compacto',
    toolbarDensityStandard: 'Estándar',
    toolbarDensityComfortable: 'Cómodo',
    toolbarColumns: 'Columnas',
    toolbarColumnsLabel: 'Seleccionar columnas',
    toolbarFilters: 'Filtros',
    toolbarFiltersLabel: 'Mostrar filtros',
    toolbarFiltersTooltipHide: 'Ocultar filtros',
    toolbarFiltersTooltipShow: 'Mostrar filtros',
    toolbarFiltersTooltipActive: (count) => `${count} filtros activos`,
    toolbarExport: 'Exportar',
    toolbarExportLabel: 'Exportar',
    toolbarExportCSV: 'Descargar como CSV',
    toolbarExportPrint: 'Imprimir',
    toolbarQuickFilterPlaceholder: 'Buscar...',
    columnsPanelTextFieldLabel: 'Buscar columna',
    columnsPanelTextFieldPlaceholder: 'Título de columna',
    columnsPanelDragIconLabel: 'Reordenar columna',
    columnsPanelShowAllButton: 'Mostrar todas',
    columnsPanelHideAllButton: 'Ocultar todas',
    columnMenuShowHideAll:'Mostrar/Ocultar todas',
    filterPanelAddFilter: 'Añadir filtro',
    filterPanelDeleteIconLabel: 'Eliminar',
    filterPanelLinkOperator: 'Operadores lógicos',
    filterPanelOperators: 'Operadores',
    filterPanelInputPlaceholder: 'Valor',
    filterOperatorContains: 'contiene',
    filterOperatorEquals: 'es igual a',
    filterOperatorStartsWith: 'empieza por',
    filterOperatorEndsWith: 'termina en',
    filterOperatorIs: 'es',
    filterOperatorNot: 'no es',
    filterOperatorAfter: 'es posterior a',
    filterOperatorOnOrAfter: 'es igual o posterior a',
    filterOperatorBefore: 'es anterior a',
    filterOperatorOnOrBefore: 'es igual o anterior a',
    filterOperatorIsEmpty: 'está vacío',
    filterOperatorIsNotEmpty: 'no está vacío',
    filterOperatorIsAnyOf: 'es cualquiera de',
    filterPanelInputLabel: 'Filtrar valor',
    filterPanelColumns: 'Columnas',
    filterPanelOperator: 'Operador',
    columnMenuLabel: 'Menú',
    columnMenuShowColumns: 'Mostrar columnas',
    columnMenuFilter: 'Filtrar',
    columnMenuHideColumn: 'Ocultar',
    columnMenuUnsort: 'Desordenar',
    columnMenuSortAsc: 'Orden ascendente',
    columnMenuSortDesc: 'Orden descendente',
    columnHeaderFiltersTooltipActive: (count) => `${count} filtros activos`,
    columnHeaderFiltersLabel: 'Mostrar filtros',
    columnHeaderSortIconLabel: 'Ordenar',
    footerRowSelected: (count) => count !== 1 ? `${count.toLocaleString()} filas seleccionadas` : `${count.toLocaleString()} fila seleccionada`,
    footerTotalRows: 'Filas Totales:',
    checkboxSelectionHeaderName: 'Selección de casilla',
    booleanCellTrueLabel: 'Sí',
    booleanCellFalseLabel: 'No',
    actionsCellMore: 'más',
    pinToLeft: 'Fijar a la izquierda',
    pinToRight: 'Fijar a la derecha',
    unpin: 'Desfijar',
    treeDataGroupingHeaderName: 'Agrupación',
    treeDataExpand: 'ver hijos',
    treeDataCollapse: 'ocultar hijos',
    groupingColumnHeaderName: 'Agrupación',
    groupColumn: (name) => `Agrupar por ${name}`,
    unGroupColumn: (name) => `Dejar de agrupar por ${name}`,
  };